---
title: "analyze unspecified ODs"
author: "Zeynep Hasgul"
date: "13/01/2023"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
#library(tidycensus)
`%!in%` <- Negate(`%in%`)
#census_api_key("5512ff2f4dc8ad3053285afb019b439ed4bfab34", install=TRUE)
#census_api_key(Sys.getenv("CENSUS_API_KEY"))
```

import OD data
```{r}
all_ODs <- read.csv("/Users/zeynephasgul/Desktop/COVID revision/NCHS_all_ODs.csv") 
```

concatenate ICD columns
```{r}
all_ODs <- all_ODs %>% 
  unite(all_codes, record_1:record_20, sep = "|", remove=TRUE)
```

total OD's
```{r}
total_death <- all_ODs %>% 
  count(year, sort = TRUE)

```

assign drug category to known and unspecified 
```{r}
known_drugs <- "T360|T361|T362|T363|T364|T365|T366|T367|T368|T369|
T370|T371|T372|T373|T374|T375|T376|T377|T378|T379|
T380|T381|T382|T383|T384|T385|T386|T387|T388|T389|
T390|T391|T392|T393|T394|T395|T396|T397|T398|T399|
T400|T401|T402|T403|T404|T405|T406|T407|T408|T409|
T410|T411|T412|T413|T414|T415|T416|T417|T418|T419|
T420|T421|T422|T423|T424|T425|T426|T427|T428|T429|
T430|T431|T432|T433|T434|T435|T436|T437|T438|T439|
T440|T441|T442|T443|T444|T445|T446|T447|T448|T449|
T450|T451|T452|T453|T454|T455|T456|T457|T458|T459|
T460|T461|T462|T463|T464|T465|T466|T467|T468|T469|
T470|T471|T472|T473|T474|T475|T476|T477|T478|T479|
T480|T481|T482|T483|T484|T485|T486|T487|T488|T489|
T490|T491|T492|T493|T494|T495|T496|T497|T498|T499|
T500|T501|T502|T503|T504|T505|T506|T507|T508|
"
unspecified_od <-"T509"
```


name each overdose by known or unspecified
```{r}
ODs_classified <- all_ODs %>%
  mutate(
    known_drugs = case_when(grepl(known_drugs, all_codes) ~ 1,
                       TRUE ~ 0),
    unspecified = case_when(grepl(unspecified_od, all_codes) ~ 1,
                      TRUE ~ 0),
    )

```


assign mutually exclusive labels to unclassifed drug overdoses
```{r}
unclassified_ODs_mut_excl <- ODs_classified %>%
  mutate(
    unclassified_only = case_when(
      known_drugs == 0 &
        unspecified == 1 ~ 1,
      TRUE ~ 0
    ))
```


```{r}
total_unspecified_od_summary <- unclassified_ODs_mut_excl %>% 
  group_by(year) %>% 
  count(unclassified_only, sort = TRUE)

```








